# [START swagger]
swagger: "2.0"
info:
  description: "ISB-CGC API Endpoint, version 4"
  title: "ISB-CGC API v4"
  version: "4.0.0"
host: "api-v4-dot-isb-cgc.appspot.com"
# [END swagger]
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
paths:
  /apiv4:
    post:
      description: "Basic Response."
      operationId: "root-post"
      produces:
      - "application/json"
      responses:
        200:
          description: "Basic Response"
          schema:
            $ref: "#/definitions/responseMessage"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"
    get:
      description: "Basic Response."
      operationId: "root-get"
      produces:
      - "application/json"
      responses:
        200:
          description: "Basic Response"
          schema:
            $ref: "#/definitions/responseMessage"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"

  /cohorts:
    get:
      description: "Get a list of the user's cohorts."
      operationId: "getCohorts"
      produces:
      - "application/json"
      responses:
        200:
          description: "A list of the user's cohorts."
          schema:
            $ref: "#/definitions/cohortListResponse"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"
      security:
        - google_id_token: []

  /cohorts/{cohort_id}:
    get:
      description: "Get information for the specified cohort."
      operationId: "getCohort"
      produces:
      - "application/json"
      responses:
        200:
          description: "Information about the specified cohort"
          schema:
            $ref: "#/definitions/cohortResponse"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"
      security:
        - google_id_token: []

  /cohorts/{cohort_id}/file_manifest:
    get:
      description: "Retrieve a cohort's file manifest."
      operationId: "getCohortFileManifest"
      produces:
        - "application/json"
      parameters:
        - name: cohort_id
          in: path
          description: "Numeric ISB-CGC Cohort ID"
          type: integer
          required: true
      responses:
        200:
          description: "File manifest for the specified cohort."
          schema:
            $ref: "#/definitions/cohortFileManifestResponse"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"
      security:
        - google_id_token: []
    post:
      description: "Retrieve a cohort's file manifest based on filters provided."
      operationId: "postCohortFileManifest"
      produces:
        - "application/json"
      parameters:
        - name: cohort_id
          in: path
          description: "Numeric ISB-CGC Cohort ID"
          type: integer
          required: true
        - name: "filters"
          in: body
          description: "Filters to apply to the file manifest."
          schema:
            type: object
            properties:
              program:
                type: string
              disease_code:
                type: string
              project:
                type: string
      responses:
        200:
          description: "File manifest for the specified cohort."
          schema:
            $ref: "#/definitions/cohortFileManifestResponse"
        500:
          description: "Server error message"
          schema:
            $ref: "#/definitions/errorMessage"
      security:
        - google_id_token: []

definitions:
  responseMessage:
    type: "object"
    properties:
      message:
        type: "string"
      code:
        type: "integer"
  cohortListResponse:
    type: "object"
    properties:
      data:
        type: "string"
      code:
        type: "integer"
  cohortResponse:
    type: "object"
    properties:
      data:
        type: "string"
      code:
        type: "integer"
  cohortFileManifestResponse:
    type: "object"
    properties:
      data:
        type: "string"
      code:
        type: "integer"
  errorMessage:
    type: "object"
    properties:
      message:
        type: "string"
      code:
        type: "integer"

## [START securityDef]
securityDefinitions:
#  # This section configures basic authentication with an API key.
#  api_key:
#    type: "apiKey"
#    name: "key"
#    in: "query"
## [END securityDef]
#  # This section configures authentication using Google API Service Accounts
#  # to sign a json web token. This is mostly used for server-to-server
#  # communication.
#  google_jwt:
#    authorizationUrl: ""
#    flow: "implicit"
#    type: "oauth2"
#    # This must match the 'iss' field in the JWT.
#    x-google-issuer: "jwt-client.endpoints.sample.google.com"
#    # Update this with your service account's email address.
#    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/YOUR-SERVICE-ACCOUNT-EMAIL"
#    # This must match the "aud" field in the JWT. You can add multiple audiences to accept JWTs from multiple clients.
#    x-google-audiences: "echo.endpoints.sample.google.com"
#  # This section configures authentication using Google App Engine default
#  # service account to sign a json web token. This is mostly used for
#  # server-to-server communication.
#  gae_default_service_account:
#    authorizationUrl: ""
#    flow: "implicit"
#    type: "oauth2"
#    # Replace YOUR-CLIENT-PROJECT-ID with your client project ID.
#    x-google-issuer: "YOUR-CLIENT-PROJECT-ID@appspot.gserviceaccount.com"
#    # Replace YOUR-CLIENT-PROJECT-ID with your client project ID.
#    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/YOUR-CLIENT-PROJECT-ID@appspot.gserviceaccount.com"
#    # This must match the "aud" field in the JWT. You can add multiple audiences to accept JWTs from multiple clients.
#    x-google-audiences: "echo.endpoints.sample.google.com"
#  # This section configures authentication using a service account
#  # to sign a json web token. This is mostly used for server-to-server
#  # communication.
#  google_service_account:
#    authorizationUrl: ""
#    flow: "implicit"
#    type: "oauth2"
#    # Replace YOUR-SERVICE-ACCOUNT-EMAIL with your service account email.
#    x-google-issuer: "YOUR-SERVICE-ACCOUNT-EMAIL"
#    # Replace YOUR-SERVICE-ACCOUNT-EMAIL with your service account email.
#    x-google-jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/YOUR-SERVICE-ACCOUNT-EMAIL"
#    # This must match the "aud" field in the JWT. You can add multiple audiences to accept JWTs from multiple clients.
#    x-google-audiences: "echo.endpoints.sample.google.com"
#  # This section configures authentication using Google OAuth2 ID Tokens.
#  # ID Tokens can be obtained using OAuth2 clients, and can be used to access
#  # your API on behalf of a particular user.
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    # Your OAuth2 client's Client ID must be added here. You can add multiple client IDs to accept tokens form multiple clients.
    x-google-audiences: "907668440978-ej0l2i5e9qqb5lt0tge1klh1ht0ci6ea.apps.googleusercontent.com"
