version: 2.1
commands:
  deployment_setup:
    steps:
      - run:
          name: "Set the Tier"
          command: |
            TIER=DEV
            if [[ ${CIRCLE_BRANCH} =~ idc-(prod|uat|test).* ]]; then
              TIER=$(awk -F[\-_] '{print toupper($2)}' \<<< ${CIRCLE_BRANCH})
            fi
            echo "export TIER=${TIER}" >> $BASH_ENV
            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
      - run:
          name: "Assign Project-level vars"
          command: |
            if [ ! -f deployment.key.json ]; then
              echo "Deployment JSON keyfile not found - loading from CircleCI."
              KEY=${DEPLOYMENT_KEY_IDC_DEV}
            else
              echo "Deployment JSON keyfile found."
              KEY="NA"
            fi
            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_IDC_DEV}
            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_IDC_DEV}
            BUCKET=${DEPLOYMENT_BUCKET_IDC_DEV}
            if [[ ${TIER} == "DEV" ]]; then
              echo "Using default developement project ${PROJECT_ID} and related deployment SA and bucket."
            elif [[ ${TIER} == "UAT" ]]; then
              KEY=${DEPLOYMENT_KEY_IDC_UAT}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_IDC_UAT}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_IDC_UAT}
              BUCKET=${DEPLOYMENT_BUCKET_IDC_UAT}
            elif [[ ${TIER} == "TEST" ]]; then
              KEY=${DEPLOYMENT_KEY_IDC_TEST}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_IDC_TEST}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_IDC_TEST}
              BUCKET=${DEPLOYMENT_BUCKET_IDC_TEST}
            elif [[ ${TIER} == "PROD" ]]; then
              KEY=${DEPLOYMENT_KEY_IDC_PROD}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_IDC_PROD}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_IDC_PROD}
              BUCKET=${DEPLOYMENT_BUCKET_IDC_PROD}
            else
              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
              exit 1
            fi

            echo "export DEPLOYMENT_TIER=${TIER}" >> $BASH_ENV
            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV
            echo "export DEPLOYMENT_BUCKET=${BUCKET}" >> $BASH_ENV

            echo "Project settings assigned:"
            echo "Deployment client: ${CLIENT_EMAIL}"
            echo "Deployment project: ${PROJECT_ID}"
            echo "Deployment bucket: gs://${BUCKET}"

  deployment_config:
    steps:
      - run:
          name: "Set tier-specific configuration file"
          command: |
            sudo -E /bin/bash ./shell/pull_config.sh
            xargs -a deployment_config.txt -I{} echo "export {}" >> $BASH_ENV
            # Set up test/deployment database values
            echo "export MYSQL_ROOT_PASSWORD_BUILD=idc" >> $BASH_ENV
            echo "export DATABASE_NAME_BUILD=build_database" >> $BASH_ENV
            echo "export DATABASE_PASSWORD_BUILD=idc" >> $BASH_ENV
            echo "export DATABASE_USER_BUILD=django-user" >> $BASH_ENV
            echo "export DATABASE_HOST_BUILD=127.0.0.1" >> $BASH_ENV

  auth:
    steps:
      - run:
          name: "Service Account Auth and Project Settings"
          command: |
            sudo -E /bin/bash ./shell/gcloud_authenticate.sh

  install_cloud_sdk:
    steps:
      - run:
          name: "Install CloudSDK"
          command: |
            echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
            sudo apt-get install ca-certificates
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update -qq
            sudo apt-get -y install google-cloud-sdk

jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/IDC-API
    docker:
      - image: cimg/python:3.11
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "isb"
          MYSQL_ROOT_PASSWORD: "isb"
    steps:
      - checkout
      - run:
          name: Fix for bug with Git and Ubuntu 20+
          command: |
            SHA=$(git rev-list -1 HEAD)
            echo "export APP_SHA=${SHA:0:7}" >> $BASH_ENV
      - run:
          name: Set Python Path
          command: |
            echo "export PYTHONPATH=/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib" >> $BASH_ENV
      - restore_cache:
          keys:
            - idc-api-lib-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - idc-api-google-deps-{{ checksum "shell/install-deps.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - save_cache:
          key: idc-api-lib-{{ checksum "requirements.txt" }}
          paths:
            - ./lib
      - install_cloud_sdk
      - deployment_setup
      - auth
      - deployment_config
      - run:
          name: Staging
          command: |
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
      - run:
          name: Compare Config
          command: |
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/deployment_config.txt"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${ENV_FILE}"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${API_APP_YAML}"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${OPEN_API_V1_YAML}"
            sudo -E /bin/bash ./shell/compareConfig.sh "gs://${DEPLOYMENT_BUCKET}/${OPEN_API_V2_YAML}"
      - save_cache:
          key: idc-api-{{ .Branch }}-{{ .Revision }}-{{ epoch }}
          paths:
            - ./api
            - ./shell
            - ./Dockerfile
            - ./app.yaml
            - ./openapi-appengine.v1.yaml
            - ./openapi-appengine.v2.yaml
            - ./settings.py
            - ./gunicorn.conf.py
            - ./txt
            - ./json
            - ./.env

  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/IDC-API
    docker:
      - image: cimg/python:3.11
    steps:
      - restore_cache:
          keys:
            - idc-api-{{ .Branch }}-{{ .Revision }}-
      - restore_cache:
          keys:
            - idc-api-google-deps-
      - install_cloud_sdk
      - deployment_setup
      - auth
      - deployment_config
      - deploy:
          name: Deployment
          command: |
            sudo -E /bin/bash ./shell/unpack_for_deployment.sh
            sudo -E gcloud endpoints services deploy ./openapi-appengine.v1.yaml  ./openapi-appengine.v2.yaml
            sudo -E gcloud config set app/cloud_build_timeout 1600
            sudo -E gcloud app deploy --verbosity=debug ./app.yaml --service-account=${API_RUNTIME_SA_NAME} --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - master
                - idc-test
                - idc-uat
                - idc-prod
