version: 2.1
commands:
  deployment_setup:
    steps:
      - run:
          name: "Set the Tier"
          command: |
            TIER=DEV
            if [[ ${CIRCLE_BRANCH} =~ isb-cgc-(prod|uat|test).* ]]; then
              TIER=$(awk -F- '{print toupper($3)}' \<<< ${CIRCLE_BRANCH})
            fi
            echo "export TIER=${TIER}" >> $BASH_ENV
            echo "Tier was identified as ${TIER} for branch ${CIRCLE_BRANCH}"
      - run:
          name: "Assign Project-level vars"
          command: |
            KEY=${DEV_PRIVATE_KEY_FOR_V2}
            CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC}
            PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC}
            if [[ ${TIER} == "PROD" ]] || [[ ${TIER} == "DEV" ]]; then
              echo "Using default project ${PROJECT_ID} and related deployment SA."
            elif [[ ${TIER} == "UAT" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CGC_UAT}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_UAT}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC}
            elif [[ ${TIER} == "TEST" ]]; then
              KEY=${DEPLOYMENT_KEY_ISB_CGC_TEST}
              CLIENT_EMAIL=${DEPLOYMENT_CLIENT_EMAIL_ISB_CGC_TEST}
              PROJECT_ID=${DEPLOYMENT_PROJECT_ID_ISB_CGC}
            else
              echo "[ERROR] - Unrecognized tier: ${TIER} - exitng."
              exit 1
            fi

            echo "export DEPLOYMENT_KEY=\"${KEY}\"" >> $BASH_ENV
            echo "export DEPLOYMENT_CLIENT_EMAIL=${CLIENT_EMAIL}" >> $BASH_ENV
            echo "export DEPLOYMENT_PROJECT_ID=${PROJECT_ID}" >> $BASH_ENV

      - run:
          name: "Set tier-specific configuration file"
          command: |
            CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_DEV}
            if [[ ${TIER} == "PROD" ]]; then
              echo "Deployment configuration set for production."
              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_PROD}
            elif [[ ${TIER} == "UAT" ]]; then
              echo "Deployment configuration set for production."
              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_UAT}
            elif [[ ${TIER} == "TEST" ]]; then
              echo "Deployment configuration set for production."
              CONFIG_FILE=${DEPLOYMENT_CONFIG_FILE_TEST}
            elif [[ ${TIER} == "DEV" ]]; then
              echo "Deployment configuration set for production."
            else
              echo "[ERROR] - Unrecognized tier: ${TIER}"
              CONFIG_FILE=
            fi

            if [[ -n $CONFIG_FILE ]]; then
              echo "export DEPLOYMENT_CONFIG_FILE=${CONFIG_FILE}" >> $BASH_ENV
            else
              echo "[ERROR] Couldn't assign deployment configuration file - exiting."
            fi

jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    working_directory: ~/ISB-CGC-API
    docker:
      - image:  circleci/python:3.7.0-stretch
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "isb"
          MYSQL_ROOT_PASSWORD: "isb"
    steps:
      - checkout
      - run:
          name: Set Python Path
          command: |
            echo "export PYTHONPATH=/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib" >> $BASH_ENV
      - restore_cache:
          keys:
            - isb-cgc-api-lib-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - isb-cgc-api-google-deps-{{ checksum "shell/install-deps.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - save_cache:
          key: isb-cgc-api-lib-{{ checksum "requirements.txt" }}
          paths:
            - ./lib
      - deployment_setup
      - save_cache:
          key: isb-cgc-api-google-deps-{{ checksum "./shell/install-deps.sh" }}
          paths:
            - ./google-cloud-sdk
            - ./google_appengine
      - run:
          name: Auth and Staging
          command: |
            sudo -E /bin/sh ./shell/gcloud_authenticate.sh
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
      - save_cache:
          key: isb-cgc-api-{{ epoch }}
          paths:
            - ./apiv4
            - ./shell
            - ./ISB-CGC-Common
            - ./Dockerfile
            - ./app.yaml
            - ./openapi-appengine.yaml
            - ./settings.py
            - ./txt
            - ./json
            - ./.env

  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    docker:
      - image:  circleci/python:3.7.0-stretch
    working_directory: ~/ISB-CGC-API
    steps:
      - restore_cache:
          keys:
            - isb-cgc-api-
      - restore_cache:
          keys:
            - isb-cgc-api-google-deps-
      - run:
          name: Install CloudSDK
          command: |
            echo "export CLOUDSDK_CORE_DISABLE_PROMPTS=1" >> $BASH_ENV
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get -y --allow-downgrades install google-cloud-sdk=251.0.0-0
      - deploy:
          command: |
            sudo -E /bin/bash ./shell/gcloud_authenticate.sh
            sudo -E /bin/bash ./shell/unpack_for_deployment.sh
            sudo -E gcloud endpoints services deploy openapi-appengine.yaml
            sudo -E gcloud app deploy --verbosity=debug ./app.yaml --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - master
                - isb-cgc-test
                - isb-cgc-uat
                - isb-cgc-prod
