version: 2
jobs:
  build_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    name: Building Deployment Container
    working_directory: ~/ISB-CGC-API
    docker:
      - image: circleci/python:2.7.15-stretch
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_USER: ubuntu
          MYSQL_PASSWORD: "isb"
          MYSQL_ROOT_PASSWORD: "isb"
    steps:
      - checkout
      - run:
          name: Set Python Path
          command: |
            echo "export PYTHONPATH=/home/circleci/${CIRCLE_PROJECT_REPONAME}:/home/circleci/${CIRCLE_PROJECT_REPONAME}/lib" >> $BASH_ENV
      - restore_cache:
          keys:
            - isb-cgc-api-lib-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - isb-cgc-api-google-deps-{{ checksum "shell/install-deps.sh" }}
      - run:
          name: Install Dependencies
          command: |
            sudo -E /bin/bash ./shell/install-deps.sh
      - save_cache:
          key: isb-cgc-api-lib-{{ checksum "requirements.txt" }}
          paths:
            - ./lib
      - save_cache:
          key: isb-cgc-api-google-deps-{{ checksum "./shell/install-deps.sh" }}
          paths:
            - ./google-cloud-sdk
            - ./google_appengine
      - run:
          name: Auth and Staging
          command: |
            sudo -E /bin/sh ./shell/gcloud_authenticate.sh
            sudo -E /bin/bash ./shell/gcloud-pull-staging-files.sh
      - save_cache:
          key: isb-cgc-api-{{ epoch }}
          paths:
            - ./cohorts
            - ./shell
            - ./ISB-CGC-Common
            - ./lib
            - ./appengine_config.py
            - ./main.py
            - ./app.yaml
            - ./openapi-appengine.yaml
            - ./settings.py
            - ./txt
            - ./json
            - ./.env

  deploy_job:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    name: Deploy to AppEngine Flex
    docker:
      - image: circleci/python:2.7.15-stretch
    working_directory: ~/ISB-CGC-API
    steps:
      - restore_cache:
          keys:
            - isb-cgc-api-
      - restore_cache:
          keys:
            - isb-cgc-api-google-deps-
      - deploy:
          command: |
            sudo -E /bin/bash ./shell/gcloud_authenticate.sh
            sudo -E /bin/bash ./shell/unpack_for_deployment.sh
            sudo -E ./google-cloud-sdk/bin/gcloud endpoints services deploy openapi-appengine.yaml
            sudo -E ./google-cloud-sdk/bin/gcloud app deploy --verbosity=debug ./app.yaml --quiet
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only: api-v4
